const data = [
  {
    id: 1,
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    name: "tester 1",
    company: "ABC company",
    worker: "worker",
    inducted: "yes",
    prestart: "yes",
    timein: "09:30AM",
    timeout:"06:30PM",
  },
  {
    id: 2,
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    name: "tester 2",
    company: "DEF company",
    worker: "visitor",
    inducted: "yes",
    prestart: "yes",
    timein: "09:00AM",
    timeout:"06:00PM",
  },
  {
    id: 3,
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    name: "tester 3",
    company: "ABC company",
    worker: "worker",
    inducted: "yes",
    prestart: "yes",
    timein: "08:30AM",
    timeout:"06:30PM",
  },
  {
    id: 4,
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    name: "tester 4",
    company: "DEF company",
    worker: "visitor",
    inducted: "yes",
    prestart: "yes",
    timein: "09:30AM",
    timeout:"05:30PM",
  },
  {
    id: 5,
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    name: "tester 5",
    company: "ABc company",
    worker: "worker",
    inducted: "yes",
    prestart: "yes",
    timein: "09:30AM",
    timeout:"05:30PM",
  },
  {
    id: 6,
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    name: "tester 6",
    company: "DEF company",
    worker: "visitor",
    inducted: "yes",
    prestart: "yes",
    timein: "09:30AM",
    timeout:"05:30PM",
  },
  {
    id: 7,
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    name: "tester 7",
    company: "ABC company",
    worker: "worker",
    inducted: "yes",
    prestart: "yes",
    timein: "09:30AM",
    timeout:"05:30PM",
  },
  {
    id: 8,
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    name: "tester 8",
    company: "DEF company",
    worker: "visitor",
    inducted: "yes",
    prestart: "yes",
    timein: "09:30AM",
    timeout:"05:30PM",
  },
  {
    id: 9,
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    name: "tester 2",
    company: "DEF company",
    worker: "worker",
    inducted: "yes",
    prestart: "yes",
    timein: "09:30AM",
    timeout:"05:30PM",
  },
  {
    id: 10,
    image: "https://avatars.githubusercontent.com/u/1?v=4",
    name: "tester 10",
    company: "DEF company",
    worker: "visitor",
    inducted: "yes",
    prestart: "yes",
    timein: "09:30AM",
    timeout:"05:30PM",
  },
];

export default data;
